name: Node.js Backend CI

on:
  push:
    branches: ["main"]

jobs:
  backend:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: ./backend
        run: npm install

      - name: Run backend and test
        working-directory: ./backend
        run: |
          node server.js &
          SERVER_PID=$!

          echo "Waiting for backend..."
          
          # wait until server responds
          for i in {1..10}; do
            if curl -s http://localhost:5000/health; then
              echo " Backend is up"
              break
            fi
            echo "Retrying..."
            sleep 2
          done

          # final check (fail if not working)
          curl -f http://localhost:5000/health

          kill $SERVER_PID